FROM golang:latest
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 \
    GOPROXY="https://goproxy.cn,direct"
WORKDIR /go/work
COPY . .
VOLUME /go/work/log
RUN go build ./cmd/job/main.go
ENTRYPOINT ["./main"]